import type { PrerequisiteRow } from "./types";

/** Live catalog from `/admin/prerequisites`, minus `Test` (kept archived). */
export const INITIAL_PREREQUISITES: PrerequisiteRow[] = [
  {
    id: "background-check-consent",
    name: "Background Check Consent",
    description: "Student confirms consent for a background check before class start.",
    inputType: "checkbox",
    requiredByDefault: true,
    expiration: "never",
    validMonths: null,
    createdOn: "2025-11-04",
    archived: false,
  },
  {
    id: "cpr-certification",
    name: "CPR Certification",
    description: "Upload a current CPR card. Valid for 24 months from the issue date.",
    inputType: "file",
    requiredByDefault: true,
    expiration: "duration_from_issue",
    validMonths: 24,
    createdOn: "2025-09-18",
    archived: false,
  },
  {
    id: "emergency-contact",
    name: "Emergency Contact",
    description: "Enter the name and contact information for your emergency contact.",
    inputType: "text",
    requiredByDefault: true,
    expiration: "never",
    validMonths: null,
    createdOn: "2025-09-18",
    archived: false,
  },
  {
    id: "high-school-graduation",
    name: "High School Graduation Date",
    description: "Date the student graduated high school or completed a GED.",
    inputType: "date",
    requiredByDefault: true,
    expiration: "never",
    validMonths: null,
    createdOn: "2025-10-02",
    archived: false,
  },
  {
    id: "immunization-record",
    name: "Immunization Record",
    description: "Upload immunization records. Students provide the expiration date.",
    inputType: "file",
    requiredByDefault: true,
    expiration: "fixed_date",
    validMonths: null,
    createdOn: "2026-01-14",
    archived: false,
  },
  {
    id: "test",
    name: "Test",
    description: "Placeholder type from the live catalog.",
    inputType: "date",
    requiredByDefault: true,
    expiration: "never",
    validMonths: null,
    createdOn: "2026-03-08",
    archived: true,
  },
];
