/**
 * Generate schema + data SQL files from the source (old) Supabase project.
 *
 * Read-only on source — no writes to either database.
 *
 * Usage:
 *   npm run migration:generate-sql
 *
 * Output: docs/migration/generated-sql/*.sql
 * Each file: CREATE TABLE (+ indexes/RLS) + INSERT rows for one table.
 * Run 00-setup-enums.sql first, then 01-auth-users.sql, then 02+ in order.
 */

import dotenv from 'dotenv';
import path from 'path';
import fs from 'fs';
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import {
  getProjectRef,
  getSupabaseCredentials,
} from './lib/migration-env';
import {
  buildCreateTableSql,
  buildEnumSql,
  fetchOpenApiSchema,
  TableDef,
} from './lib/openapi-schema';
import {
  getTableExtras,
  logsSequenceResetSql,
} from './lib/table-extras';

const PAGE_SIZE = 1000;

/** FK-safe run order on the NEW database. */
const TABLE_ORDER = [
  'courses',
  'locations',
  'classes',
  'students',
  'enrollments',
  'transactions',
  'waitlist',
  'payments',
  'admins',
  'logs',
  'invoices_to_import',
  'email_logs',
] as const;

function loadEnv() {
  const candidates = [
    path.resolve(__dirname, '../.env.local'),
    path.resolve(__dirname, '../apps/webapp/.env.local'),
    path.resolve(__dirname, '../.env'),
  ];

  for (const envPath of candidates) {
    if (fs.existsSync(envPath)) {
      dotenv.config({ path: envPath });
    }
  }
}

function sqlString(value: string): string {
  const cleaned = value.replace(/\r/g, '').replace(/\n/g, ' ').trim();
  return `'${cleaned.replace(/\\/g, '\\\\').replace(/'/g, "''")}'`;
}

function sqlLiteral(value: unknown): string {
  if (value === null || value === undefined) {
    return 'NULL';
  }

  if (typeof value === 'boolean') {
    return value ? 'TRUE' : 'FALSE';
  }

  if (typeof value === 'number') {
    return Number.isFinite(value) ? String(value) : 'NULL';
  }

  if (typeof value === 'object') {
    return `${sqlString(JSON.stringify(value))}::jsonb`;
  }

  return sqlString(String(value));
}

function buildInsertBlock(
  tableName: string,
  rows: Record<string, unknown>[]
): string {
  if (rows.length === 0) {
    return `-- No rows to insert for ${tableName}\n`;
  }

  const columns = Object.keys(rows[0]);
  const columnList = columns.map((c) => `"${c}"`).join(', ');
  const lines: string[] = [`-- Data: ${rows.length} row(s)`, ''];

  for (const row of rows) {
    const values = columns.map((col) => sqlLiteral(row[col])).join(', ');
    lines.push(
      `INSERT INTO public.${tableName} (${columnList}) VALUES (${values}) ON CONFLICT (id) DO NOTHING;`
    );
  }

  lines.push('');
  return lines.join('\n');
}

function patchLogsTable(table: TableDef): TableDef {
  return {
    ...table,
    columns: table.columns.map((col) => {
      if (col.name !== 'id') return col;
      return {
        ...col,
        sqlType: 'BIGINT GENERATED BY DEFAULT AS IDENTITY',
        defaultSql: null,
        foreignKey: null,
      };
    }),
  };
}

async function fetchAllRows(
  supabase: SupabaseClient,
  tableName: string
): Promise<Record<string, unknown>[]> {
  const rows: Record<string, unknown>[] = [];
  let from = 0;

  while (true) {
    const to = from + PAGE_SIZE - 1;
    const { data, error } = await supabase
      .from(tableName)
      .select('*')
      .range(from, to);

    if (error) {
      throw new Error(`${tableName}: ${error.message}`);
    }

    const batch = data ?? [];
    rows.push(...batch);

    if (batch.length < PAGE_SIZE) {
      break;
    }

    from += PAGE_SIZE;
  }

  return rows;
}

async function fetchAuthUsers(supabase: SupabaseClient) {
  const users: Record<string, unknown>[] = [];
  let page = 1;

  while (true) {
    const { data, error } = await supabase.auth.admin.listUsers({
      page,
      perPage: PAGE_SIZE,
    });

    if (error) {
      throw new Error(`auth.users: ${error.message}`);
    }

    const batch = data.users ?? [];
    users.push(
      ...batch.map((user) => ({
        id: user.id,
        email: user.email,
        phone: user.phone,
        created_at: user.created_at,
        updated_at: user.updated_at,
        last_sign_in_at: user.last_sign_in_at,
        email_confirmed_at: user.email_confirmed_at,
        phone_confirmed_at: user.phone_confirmed_at,
        confirmed_at: user.confirmed_at,
        banned_until: user.banned_until,
        is_anonymous: user.is_anonymous,
        app_metadata: user.app_metadata,
        user_metadata: user.user_metadata,
      }))
    );

    if (batch.length < PAGE_SIZE) {
      break;
    }

    page += 1;
  }

  return users;
}

/** Students on source often exist without auth.users rows (checkout-created). */
function mergeAuthUsersFromStudents(
  authUsers: Record<string, unknown>[],
  students: Record<string, unknown>[]
): { all: Record<string, unknown>[]; stubs: Record<string, unknown>[] } {
  const authIds = new Set(authUsers.map((user) => String(user.id)));
  const stubs: Record<string, unknown>[] = [];

  for (const student of students) {
    const id = String(student.id);
    if (authIds.has(id)) continue;

    const email = student.email ? String(student.email).trim() : '';
    if (!email) {
      console.warn(
        `  ⚠️  Student ${id} has no email — skipping auth stub`
      );
      continue;
    }

    const createdAt =
      student.created_at ?? student.updated_at ?? new Date().toISOString();

    stubs.push({
      id,
      email,
      phone: null,
      created_at: createdAt,
      updated_at: student.updated_at ?? createdAt,
      last_sign_in_at: null,
      email_confirmed_at: createdAt,
      phone_confirmed_at: null,
      confirmed_at: createdAt,
      banned_until: null,
      is_anonymous: false,
      app_metadata: { provider: 'email', providers: ['email'] },
      user_metadata: { email_verified: true },
      _comment: `stub auth user for student without auth.users row (${student.full_name ?? email})`,
    });
    authIds.add(id);
  }

  return { all: [...authUsers, ...stubs], stubs };
}

function sqlPhone(value: unknown): string {
  if (value === null || value === undefined) return 'NULL';
  const trimmed = String(value).trim();
  if (!trimmed) return 'NULL';
  return sqlString(trimmed);
}

function buildAuthUsersSql(
  users: Record<string, unknown>[],
  options?: { headerLines?: string[] }
): string {
  const header = options?.headerLines ?? [
    '-- auth.users + auth.identities (schema pre-exists on Supabase projects)',
    '-- Run on the NEW project BEFORE students / admins.',
    '-- Includes stub auth rows for students that had no auth.users row on source.',
    '-- Users sign in via email OTP — no passwords are copied.',
    '',
    'BEGIN;',
    '',
  ];

  if (users.length === 0) {
    return [...header, 'COMMIT;', ''].join('\n');
  }

  const lines = [...header];

  for (const user of users) {
    const id = sqlString(String(user.id));
    const email = user.email ? sqlString(String(user.email).trim()) : 'NULL';
    const phone = sqlPhone(user.phone);
    const appMeta = sqlLiteral(
      user.app_metadata ?? { provider: 'email', providers: ['email'] }
    );
    const userMeta = sqlLiteral(user.user_metadata ?? {});

    lines.push(`-- ${user._comment ?? user.email ?? user.id}`);
    lines.push(`INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_token_current,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at,
  is_anonymous
)
SELECT
  (SELECT id FROM auth.instances LIMIT 1),
  ${id}::uuid,
  'authenticated',
  'authenticated',
  ${email},
  '',
  ${sqlLiteral(user.email_confirmed_at ?? user.confirmed_at ?? user.created_at)},
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  ${sqlLiteral(user.last_sign_in_at)},
  ${appMeta},
  ${userMeta},
  FALSE,
  ${sqlLiteral(user.created_at)},
  ${sqlLiteral(user.updated_at)},
  ${phone},
  ${sqlLiteral(user.phone_confirmed_at)},
  NULL,
  NULL,
  NULL,
  '',
  0,
  ${sqlLiteral(user.banned_until)},
  '',
  NULL,
  FALSE,
  NULL,
  ${user.is_anonymous ? 'TRUE' : 'FALSE'}
WHERE NOT EXISTS (SELECT 1 FROM auth.users WHERE id = ${id}::uuid);`);

    if (user.email) {
      lines.push('');
      lines.push(`INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  ${id}::uuid,
  jsonb_build_object('sub', ${id}::text, 'email', ${email}, 'email_verified', true),
  'email',
  ${id}::text,
  ${sqlLiteral(user.last_sign_in_at)},
  ${sqlLiteral(user.created_at)},
  ${sqlLiteral(user.updated_at)}
WHERE NOT EXISTS (
  SELECT 1 FROM auth.identities
  WHERE user_id = ${id}::uuid AND provider = 'email'
);`);
    }

    lines.push('');
  }

  lines.push('COMMIT;', '');
  return lines.join('\n');
}

function buildTableFile(
  tableName: string,
  table: TableDef,
  rows: Record<string, unknown>[]
): string {
  const patchedTable = tableName === 'logs' ? patchLogsTable(table) : table;

  const parts = [
    `-- ${tableName}: schema + data migration`,
    '-- Paste into the NEW Supabase project SQL Editor.',
    '-- Source database is read-only; this file only runs on the target.',
    '',
    'BEGIN;',
    '',
    buildCreateTableSql(patchedTable),
    getTableExtras(tableName),
    buildInsertBlock(tableName, rows),
  ];

  if (tableName === 'logs' && rows.length > 0) {
    parts.push(logsSequenceResetSql());
  }

  parts.push('COMMIT;', '');
  return parts.join('\n');
}

async function main() {
  loadEnv();

  const args = process.argv.slice(2);
  const outputFlagIndex = args.indexOf('--output');
  const outputDir = path.resolve(
    process.cwd(),
    outputFlagIndex >= 0 ? args[outputFlagIndex + 1]! : 'docs/migration/generated-sql'
  );

  const source = getSupabaseCredentials('source');
  const projectRef = getProjectRef(source.url);

  fs.mkdirSync(outputDir, { recursive: true });

  console.log('Generating schema + data SQL (read-only on source)\n');
  console.log(`  Source project: ${projectRef}`);
  console.log(`  Output:         ${outputDir}\n`);

  const schema = await fetchOpenApiSchema(source.url, source.serviceRoleKey);
  const supabase = createClient(source.url, source.serviceRoleKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  const manifest: Record<string, { file: string; row_count: number }> = {};

  const enumFile = '00-setup-enums.sql';
  fs.writeFileSync(
    path.join(outputDir, enumFile),
    [
      '-- Shared enum types required by courses / classes',
      '-- Run first on the NEW Supabase project.',
      '',
      'BEGIN;',
      '',
      buildEnumSql(schema.enums),
      'COMMIT;',
      '',
    ].join('\n'),
    'utf-8'
  );
  manifest.setup_enums = { file: enumFile, row_count: schema.enums.length };
  console.log(`  ${enumFile} — ${schema.enums.length} enum type(s)`);

  const authUsers = await fetchAuthUsers(supabase);
  const studentRows = await fetchAllRows(supabase, 'students');
  const { all: allAuthUsers, stubs } = mergeAuthUsersFromStudents(
    authUsers,
    studentRows
  );

  const authFile = '01-auth-users.sql';
  fs.writeFileSync(
    path.join(outputDir, authFile),
    buildAuthUsersSql(allAuthUsers),
    'utf-8'
  );
  manifest.auth_users = {
    file: authFile,
    row_count: allAuthUsers.length,
    auth_from_source: authUsers.length,
    student_stubs: stubs.length,
  };
  console.log(
    `  ${authFile} — ${allAuthUsers.length} users (${authUsers.length} from auth, ${stubs.length} student stubs)`
  );

  if (stubs.length > 0) {
    const stubFile = '01b-auth-student-stubs.sql';
    fs.writeFileSync(
      path.join(outputDir, stubFile),
      buildAuthUsersSql(stubs, {
        headerLines: [
          '-- Stub auth.users for students that had no auth.users row on source',
          '-- Run on NEW project BEFORE 05-students.sql if you already ran 01-auth-users.sql',
          '-- Safe to re-run: skips users that already exist.',
          '',
          'BEGIN;',
          '',
        ],
      }),
      'utf-8'
    );
    manifest.auth_student_stubs = { file: stubFile, row_count: stubs.length };
    console.log(`  ${stubFile} — ${stubs.length} student stub(s) only`);
  }

  let index = 2;
  for (const tableName of TABLE_ORDER) {
    const table = schema.tables.get(tableName);
    if (!table) {
      console.warn(`  ⚠️  Skipping ${tableName} — not found in source OpenAPI`);
      continue;
    }

    const rows = await fetchAllRows(supabase, tableName);
    const fileName = `${String(index).padStart(2, '0')}-${tableName}.sql`;
    fs.writeFileSync(
      path.join(outputDir, fileName),
      buildTableFile(tableName, table, rows),
      'utf-8'
    );
    manifest[tableName] = { file: fileName, row_count: rows.length };
    console.log(`  ${fileName} — schema + ${rows.length} rows`);
    index += 1;
  }

  const readme = `# Generated migration SQL (schema + data)

Generated from source project \`${projectRef}\` at ${new Date().toISOString()}.

**Read-only export from the old database.** Paste and run each file in the **new**
Supabase project SQL Editor only. The old database is never modified.

## Run order (new project)

| # | File | Contents |
|---|------|----------|
| 0 | \`00-setup-enums.sql\` | \`programming_type\`, \`programming_offering\` enums |
| 1 | \`01-auth-users.sql\` | auth users + identities (+ student stubs) |
| 1b | \`01b-auth-student-stubs.sql\` | student stubs only (if you already ran 01) |
| 2 | \`02-courses.sql\` | CREATE + 17 rows |
| 3 | \`03-locations.sql\` | CREATE + 5 rows |
| 4 | \`04-classes.sql\` | CREATE + 16 rows |
| 5 | \`05-students.sql\` | CREATE + 82 rows |
| 6 | \`06-enrollments.sql\` | CREATE + 62 rows |
| 7 | \`07-transactions.sql\` | CREATE + 56 rows |
| 8 | \`08-waitlist.sql\` | CREATE + 20 rows |
| 9 | \`09-payments.sql\` | CREATE + 0 rows |
| 10 | \`10-admins.sql\` | CREATE + 6 rows |
| 11 | \`11-logs.sql\` | CREATE + 162 rows |
| 12 | \`12-invoices_to_import.sql\` | CREATE + 22 rows |
| 13 | \`13-email_logs.sql\` | CREATE + 0 rows |

Each table file includes \`CREATE TABLE\`, indexes, RLS policies, and \`INSERT\` rows.
Files use \`BEGIN\`/\`COMMIT\` and \`ON CONFLICT (id) DO NOTHING\` for safe re-runs.

## Important

- \`01-auth-users.sql\` must run before \`05-students.sql\` and \`10-admins.sql\`.
- \`02-courses.sql\` must run before \`04-classes.sql\` (FK on \`course_code\`).
- Auth users keep the same UUIDs. Login is email OTP — passwords are not copied.
- Files contain PII — do not commit (gitignored).

## Regenerate

\`\`\`bash
npm run migration:generate-sql
\`\`\`
`;

  fs.writeFileSync(path.join(outputDir, 'README.md'), readme, 'utf-8');
  fs.writeFileSync(
    path.join(outputDir, 'manifest.json'),
    JSON.stringify(
      {
        generated_at: new Date().toISOString(),
        source_project_ref: projectRef,
        includes_schema: true,
        tables: manifest,
      },
      null,
      2
    ),
    'utf-8'
  );

  console.log('\n✅ Done. See docs/migration/generated-sql/README.md');
}

main().catch((error: unknown) => {
  console.error(
    `\n❌ ${error instanceof Error ? error.message : String(error)}`
  );
  process.exit(1);
});
