/**
 * Generate schema (+ catalog data only) SQL files for a fresh demo Supabase
 * project, from the current live/staging project's actual schema.
 *
 * Unlike migration:generate-sql (Plan 10 — clones everything, real students
 * included), this is for standing up a demo database: every table gets
 * recreated with its real, current schema, but only catalog/reference
 * tables get real data. Anything student- or transaction-shaped comes out
 * empty — no current students, enrollments, payments, or credentials carry
 * over. Auth users are not exported at all; scripts/seed-demo-students.ts
 * creates the demo personas directly on the target project.
 *
 * Usage:
 *   npm run demo:generate-sql
 *
 * Output: docs/demo/generated-sql/*.sql — paste into the NEW project's
 * SQL Editor in the printed order.
 */

import dotenv from 'dotenv';
import path from 'path';
import fs from 'fs';
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import { getProjectRef, getSupabaseCredentials } from './lib/migration-env';
import { buildCreateTableSql, buildEnumSql, fetchOpenApiSchema, TableDef } from './lib/openapi-schema';
import { getTableExtras, logsSequenceResetSql } from './lib/table-extras';
import { getDemoTableExtras } from './lib/demo-table-extras';

const PAGE_SIZE = 1000;

type DataMode = 'data' | 'schema-only';

/** FK-safe run order on the NEW database. `admins` runs early because the
 * newer tables' RLS policies subquery it. */
const TABLE_PLAN: { name: string; mode: DataMode }[] = [
  { name: 'courses', mode: 'data' },
  { name: 'locations', mode: 'data' },
  { name: 'classes', mode: 'data' },
  { name: 'admins', mode: 'schema-only' }, // seed-demo-students.ts creates the one demo admin
  { name: 'prerequisite_types', mode: 'data' },
  { name: 'template_prerequisites', mode: 'data' },
  { name: 'students', mode: 'schema-only' },
  { name: 'enrollments', mode: 'schema-only' },
  { name: 'class_prerequisites', mode: 'data' },
  { name: 'student_credentials', mode: 'schema-only' },
  { name: 'certificates', mode: 'schema-only' },
  { name: 'transactions', mode: 'schema-only' },
  { name: 'waitlist', mode: 'schema-only' },
  { name: 'payments', mode: 'schema-only' },
  { name: 'logs', mode: 'schema-only' },
  { name: 'invoices_to_import', mode: 'schema-only' },
  { name: 'email_logs', mode: 'schema-only' },
];

function loadEnv() {
  const candidates = [
    path.resolve(__dirname, '../.env.local'),
    path.resolve(__dirname, '../apps/webapp/.env.local'),
    path.resolve(__dirname, '../.env'),
  ];
  for (const envPath of candidates) {
    if (fs.existsSync(envPath)) {
      dotenv.config({ path: envPath });
    }
  }
}

function sqlString(value: string): string {
  const cleaned = value.replace(/\r/g, '').replace(/\n/g, ' ').trim();
  return `'${cleaned.replace(/\\/g, '\\\\').replace(/'/g, "''")}'`;
}

function sqlLiteral(value: unknown): string {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE';
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'NULL';
  if (typeof value === 'object') return `${sqlString(JSON.stringify(value))}::jsonb`;
  return sqlString(String(value));
}

function buildInsertBlock(tableName: string, rows: Record<string, unknown>[]): string {
  if (rows.length === 0) {
    return `-- No rows to insert for ${tableName}\n`;
  }
  const columns = Object.keys(rows[0]);
  const columnList = columns.map((c) => `"${c}"`).join(', ');
  const lines: string[] = [`-- Data: ${rows.length} row(s)`, ''];
  for (const row of rows) {
    const values = columns.map((col) => sqlLiteral(row[col])).join(', ');
    lines.push(`INSERT INTO public.${tableName} (${columnList}) VALUES (${values}) ON CONFLICT (id) DO NOTHING;`);
  }
  lines.push('');
  return lines.join('\n');
}

function patchLogsTable(table: TableDef): TableDef {
  return {
    ...table,
    columns: table.columns.map((col) =>
      col.name !== 'id'
        ? col
        : { ...col, sqlType: 'BIGINT GENERATED BY DEFAULT AS IDENTITY', defaultSql: null, foreignKey: null }
    ),
  };
}

async function fetchAllRows(supabase: SupabaseClient, tableName: string): Promise<Record<string, unknown>[]> {
  const rows: Record<string, unknown>[] = [];
  let from = 0;
  while (true) {
    const to = from + PAGE_SIZE - 1;
    const { data, error } = await supabase.from(tableName).select('*').range(from, to);
    if (error) throw new Error(`${tableName}: ${error.message}`);
    const batch = data ?? [];
    rows.push(...batch);
    if (batch.length < PAGE_SIZE) break;
    from += PAGE_SIZE;
  }
  return rows;
}

function extrasFor(tableName: string): string {
  return getTableExtras(tableName) || getDemoTableExtras(tableName);
}

function buildTableFile(tableName: string, table: TableDef, rows: Record<string, unknown>[]): string {
  const patchedTable = tableName === 'logs' ? patchLogsTable(table) : table;
  const parts = [
    `-- ${tableName}: schema${rows.length > 0 ? ' + data' : ' only (no PII carried over)'}`,
    '-- Paste into the NEW (demo) Supabase project SQL Editor.',
    '-- Source database is read-only; this file only runs on the target.',
    '',
    'BEGIN;',
    '',
    buildCreateTableSql(patchedTable),
    extrasFor(tableName),
    buildInsertBlock(tableName, rows),
  ];
  if (tableName === 'logs' && rows.length > 0) {
    parts.push(logsSequenceResetSql());
  }
  parts.push('COMMIT;', '');
  return parts.join('\n');
}

async function main() {
  loadEnv();

  const args = process.argv.slice(2);
  const outputFlagIndex = args.indexOf('--output');
  const outputDir = path.resolve(
    process.cwd(),
    outputFlagIndex >= 0 ? args[outputFlagIndex + 1]! : 'docs/demo/generated-sql'
  );

  const source = getSupabaseCredentials('source');
  const projectRef = getProjectRef(source.url);

  fs.mkdirSync(outputDir, { recursive: true });

  console.log('Generating demo schema + catalog-only SQL (read-only on source)\n');
  console.log(`  Source project: ${projectRef}`);
  console.log(`  Output:         ${outputDir}\n`);

  const schema = await fetchOpenApiSchema(source.url, source.serviceRoleKey);
  const supabase = createClient(source.url, source.serviceRoleKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  const manifest: Record<string, { file: string; row_count: number; mode: DataMode }> = {};
  const tableOfContents: string[] = [];

  const enumFile = '00-setup-enums.sql';
  fs.writeFileSync(
    path.join(outputDir, enumFile),
    ['-- Shared enum types required by courses / classes', '-- Run first on the NEW Supabase project.', '', 'BEGIN;', '', buildEnumSql(schema.enums), 'COMMIT;', ''].join('\n'),
    'utf-8'
  );
  tableOfContents.push(`| 0 | \`${enumFile}\` | enum types |`);
  console.log(`  ${enumFile} — ${schema.enums.length} enum type(s)`);

  let index = 1;
  for (const { name: tableName, mode } of TABLE_PLAN) {
    const table = schema.tables.get(tableName);
    if (!table) {
      console.warn(`  ⚠️  Skipping ${tableName} — not found in source OpenAPI`);
      continue;
    }

    const rows = mode === 'data' ? await fetchAllRows(supabase, tableName) : [];
    const fileName = `${String(index).padStart(2, '0')}-${tableName}.sql`;
    fs.writeFileSync(path.join(outputDir, fileName), buildTableFile(tableName, table, rows), 'utf-8');
    manifest[tableName] = { file: fileName, row_count: rows.length, mode };
    tableOfContents.push(`| ${index} | \`${fileName}\` | ${mode === 'data' ? `schema + ${rows.length} row(s)` : 'schema only, empty'} |`);
    console.log(`  ${fileName} — ${mode === 'data' ? `schema + ${rows.length} rows` : 'schema only'}`);
    index += 1;
  }

  const readme = `# Generated demo SQL (schema + catalog data only)

Generated from source project \`${projectRef}\` at ${new Date().toISOString()}.

**Read-only export from the live database.** Paste and run each file in order in the
**new (demo)** Supabase project's SQL Editor. The source database is never modified,
and no student, enrollment, payment, or credential data is included — those tables
are recreated empty. No auth.users are exported either; run
\`npm run demo:seed-students\` afterward to create the demo personas.

## Run order (new project)

| # | File | Contents |
|---|------|----------|
${tableOfContents.join('\n')}

Each table file includes \`CREATE TABLE\`, indexes, RLS policies (and any views,
functions, triggers, or storage buckets that table needs), and — for catalog tables
only — \`INSERT\` rows. Files use \`BEGIN\`/\`COMMIT\` and \`ON CONFLICT (id) DO NOTHING\`,
so re-running one after a partial failure is safe.

## Next steps

1. Run every file above, in order, in the new project's SQL Editor.
2. Point \`MIGRATION_*\` env vars at this new project (if not already) and run:
   \`\`\`bash
   npm run demo:seed-students
   \`\`\`
3. Point \`apps/webapp/.env.local\`'s unprefixed Supabase vars at the new project
   to run the app against it locally.

## Regenerate

\`\`\`bash
npm run demo:generate-sql
\`\`\`
`;

  fs.writeFileSync(path.join(outputDir, 'README.md'), readme, 'utf-8');
  fs.writeFileSync(
    path.join(outputDir, 'manifest.json'),
    JSON.stringify({ generated_at: new Date().toISOString(), source_project_ref: projectRef, tables: manifest }, null, 2),
    'utf-8'
  );

  console.log('\n✅ Done. See docs/demo/generated-sql/README.md');
}

main().catch((error: unknown) => {
  console.error(`\n❌ ${error instanceof Error ? error.message : String(error)}`);
  process.exit(1);
});
