-- Migration 23: Fix transaction invoice number sequence
-- BEN-1232: Fix transactions.invoice_number generation
--
-- invoice_number was a TEXT column, generated by sorting it as a string and
-- doing `data.invoice_number + 1` in JS — string concatenation, not
-- addition, once one row's value stopped looking like a clean number. Every
-- later registration read that back as "the max" and appended another
-- digit, compounding into garbage (eventually literal exponential-notation
-- text, then NULL once the number overflowed to Infinity/NaN in JS).
--
-- Run this once against EACH Supabase project independently (disposable
-- test project first to verify, then the real/production project) — paste
-- into Supabase Dashboard -> SQL Editor -> Run.
--
-- The RETURNING output from Step 1 is the before/after record — export it
-- from the SQL Editor's results grid for documentation.
--
-- Safe to re-run: the backfill is fully derived from created_at order, not
-- prior state, so re-running on unchanged data reproduces the same numbers.

BEGIN;

-- Step 1: backfill, chronological, starting at 101. Column is still TEXT
-- here on purpose — current values include garbage/NULL that can't cast
-- straight to INTEGER, so overwrite with clean digit strings first.
WITH ordered AS (
  SELECT
    id,
    invoice_number AS old_invoice_number,
    (ROW_NUMBER() OVER (ORDER BY created_at ASC) + 100) AS new_invoice_number
  FROM transactions
)
UPDATE transactions t
SET invoice_number = ordered.new_invoice_number::text
FROM ordered
WHERE t.id = ordered.id
RETURNING
  t.id,
  t.transaction_type,
  t.created_at,
  ordered.old_invoice_number,
  t.invoice_number AS new_invoice_number;

-- Step 2: now every value is a clean small integer-as-text — convert the
-- column itself so this bug class can't happen again.
ALTER TABLE transactions
  ALTER COLUMN invoice_number TYPE INTEGER USING invoice_number::integer;

-- Step 3: enforce uniqueness at the DB level. createTransaction() already
-- catches Postgres error 23505 on this column, implying a unique index may
-- already exist under a different name — harmless if so, this just adds
-- ours (drop-then-add makes it safe to re-run).
ALTER TABLE transactions
  DROP CONSTRAINT IF EXISTS transactions_invoice_number_key;
ALTER TABLE transactions
  ADD CONSTRAINT transactions_invoice_number_key UNIQUE (invoice_number);

COMMIT;
